apiVersion: v1
kind: Service
metadata:
  name: albiondata-backend
  namespace: albiondata
spec:
  ports:
    - name: http
      targetPort: 8080
      port: 8080
  selector:
    app: albiondata-backend